name: assignment-test
on: [push]

jobs:
  full-test:
    container: cuaesd/aesd-autotest:assignment4-buildroot
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up SSH for Buildroot package fetch
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - run: ./full-test.sh
